import ml_collections
from tools.utils import system


def default() -> ml_collections.ConfigDict:

    cfg = ml_collections.ConfigDict({
        'batch_size': 16,
        'pos': [[0.1, 0.1, 0.1, 0.2, 0.2, 0.2, 0.3, 0.3, 0.3, 0.4, 0.4, 0.4, 0.5, 0.5, 0.5, 0.6, 0.6, 0.6],
                [0.1, 0.1, 0.1, 0.2, 0.2, 0.2, 0.3, 0.3, 0.3, 0.4, 0.4, 0.4, 0.5, 0.5, 0.5, 0.6, 0.6, 0.6]],
        'layer_dims': [4, 20, 20, 20, 20],
        'g': [10, 10, 10, 10],
        'k': [3, 3, 3, 3],
        'grid_range': [[0, 2], [0, 2], [0, 2], [0, 2]],
        'iterations': 100,
        'preiterations': 100,
        'run_pretrain': True,
        'seed': 42,
        'seed_electrons_coords': 22,
        'init_width': 0.1,
        'core_electrons': {},
        'pretrain_method': 'hf', #'pretrain_method': 'dft',
        'pretrain_basis': 'ccpvdz',
        'pretrain_restricted': False,
        'hf_basis': 'ccpvdz',
        'hf_restricted': False,
        'hf_states': 0,
        'hf_excitation_type': 'ordered',
        'dft_xc': 'pbe,pbe',
        'dft_grid_level': 3,
        'scf_fraction': 1.0,
        'nfeatures': 4,
        'mcmc_batch_per_device': 2,
        'mcmc_steps': 10,
        'mcmc_blocks': 1,
        'mcmc_width': 0.1,
        'clip_local_energy': 5.0,
        'use_scan': False,
        'complex_output': True,
        'laplacian_method': 'default',
        't_init': 0,
        'debug': False,
        'learning_rate': 0.005,
        'learning_rate_decay': 10000.0,
        'chebyshev': True,
        'spline': False,
        'envelope_chebyshev': False,
        'envelope_spline': False,
        'envelope_simple': True,
        'add_residual': True,
        'add_bias': True,
        'external_weights': True,
        'system': {
            'molecule': [system.Atom('C', (0, 0, 0))],
            'electrons': (3, 3),
        },
        'envelope': {
            'g_envelope': 10,
            'k_envelope': 5,
            'grid_range_envelope': [0, 2],
        },
        'output': {
            'root_dir': 'outputs/default',
            'checkpoint_every': 10,
            'metrics_every': 1,
            'resume': False,
            'enable_tensorboard': True,
        },
    })
    return cfg
